### ISSUE TITLE
The All Journals screen should be divided into three sections: Private Journals, Public, and Share Journals

### ISSUE THREAD

**Issue by desaawa** [desaawa/MyJournal#7]

**Comment by desaawa** [comment]
@andela-ookwuolisa how far with this ticket?

**Comment by veryobinna** [comment]
@awadesmoline I just pushed

**Comment by desaawa** [comment]
@andela-ookwuolisa can you please raise a PR?

**Comment by desaawa** [comment]
@andela-ookwuolisa nice work on this. I will create a new ticket for you to actually make journals Public, private or shared upon creation of the journal
